version: "3.5"

services:
    es-syslog-ng:
        build: .
        hostname: syslogng
        container_name: syslogng
        volumes:
            - ./configs:/configs
            - ./scripts:/scripts
            - ./logs:/logs
        ports:
            - "0.0.0.0:514:514/udp"
            - "0.0.0.0:601:601"
        restart: always
        environment:
            - HOSTUID
            - HOSTGID
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: 10m
