#!/bin/sh
set -e

MAINCONF='/etc/syslog-ng/syslog-ng.conf'

/scripts/cleaner 7200 &

version=`syslog-ng -V | sed '/Installer-Version/!d;s/^.*: //;s/\.[0-9]*$//'`
echo '@version: '"$version"'

# Main options
@include "/configs/options.conf"

# Sources
@include "/configs/sources.conf"

# Level Filters
@include "/configs/level-filters.conf"

# Facility Filters
@include "/configs/facility-filters.conf"

# Custom configs
@include "/configs/conf.d/*.conf"
' > "$MAINCONF"

CONF='/configs/options.conf'
! [ -f "$CONF" ] && echo "Can't find config $CONF" && exit 127
[ -n "$HOSTUID" ] && sed -i '/^[ \t]*\(dir_\)\?owner(.*);$/s/(.*)/('"$HOSTUID"')/' "$CONF"
[ -n "$HOSTGID" ] && sed -i '/^[ \t]*\(dir_\)\?group(.*);$/s/(.*)/('"$HOSTGID"')/' "$CONF"
chown -R "$HOSTUID:$HOSTGID" /logs

echo "Starting syslog-ng..."

/usr/sbin/syslog-ng -f "$MAINCONF" -F -d
